export const FETCH_CATALOG_PRODUCT = 'FETCH_CATALOG_PRODUCT';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRICE_FOR_PRODUCTS = 'FETCH_PRICE_FOR_PRODUCTS';
export const FETCH_PRODUCERS = 'FETCH_PRODUCERS';