export const SET_CATALOG_PRODUCT = 'SET_CATALOG_PRODUCT';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRICE_FOR_PRODUCTS = 'SET_PRICE_FOR_PRODUCTS';
export const SET_PRODUCERS = 'SET_PRODUCERS';
