export const FETCH_PRODUCT_CART = 'FETCH_PRODUCT_CART';
export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID';
export const INCREMENT_CART_PRODUCT = 'INCREMENT_CART_PRODUCT';
export const DECREMENT_CART_PRODUCT = 'DECREMENT_CART_PRODUCT';
 