version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: config/php
    ports:
      - "8003:80"
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini`
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    ports:
      - "6000:3306"
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=teagrocery
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    container_name: phpmyadmin
    restart: unless-stopped
    links:
      - db:db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
