export const FETCH_PRODUCT_WISHLIST = 'FETCH_PRODUCT_WISHLIST';
export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID';
export const INCREMENT_WISHLIST_PRODUCT = 'INCREMENT_WISHLIST_PRODUCT';
export const DECREMENT_WISHLIST_PRODUCT = 'DECREMENT_WISHLIST_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';