export const SET_PRODUCT_WISHLIST = 'SET_PRODUCT_WISHLIST';
export const DELETE_PRODUCT_FROM_WISHLIST = 'DELETE_PRODUCT_FROM_WISHLIST';
export const WISHLIST_INCREMENT = 'WISHLIST_INCREMENT';
export const WISHLIST_DECREMENT = 'WISHLIST_DECREMENT';