export const SET_SINGLE_PRODUCT = 'SET_SINGLE_PRODUCT';
export const SET_TO_CART = 'SET_TO_CART';
export const SET_TO_WISHLIST = 'SET_TO_WISHLIST';
export const SET_FEEDS = 'SET_FEEDS';
export const SET_PRODUCT_FEEDS = 'SET_PRODUCT_FEEDS';