export const GET_EXPENSIVE_PRODUCTS = 'GET_EXPENSIVE_PRODUCTS';
export const GET_NEW_PRODUCTS = 'GET_NEW_PRODUCTS';
export const GET_RANDOM_POSTS = 'GET_RANDOM_POSTS';
export const GET_PRODUCT_TYPES = 'GET_PRODUCT_TYPES';
export const ADD_TO_NEWSLETTER = 'ADD_TO_NEWSLETTER';


