export const SET_EXPENSIVE_PRODUCTS = 'SET_EXPENSIVE_PRODUCTS';
export const SET_NEW_PRODUCTS = 'SET_NEW_PRODUCTS';
export const SET_RANDOM_POSTS_TO_STATE = 'SET_RANDOM_POSTS_TO_STATE';
export const SET_PRODUCT_TYPES = 'SET_PRODUCT_TYPES';
export const SET_TO_NEWSLETTER = 'SET_TO_NEWSLETTER';